version: "3"
services:
  krakend:
    container_name: krakend
    image: devopsfaith/krakend
    volumes:
      - .:/etc/krakend
    ports:
      - "8080:8080"
    network_mode: crm_network
    # before install loki logging docker plugin
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-retries: "5"
        loki-batch-size: "400"
        max-size: "10m"
        loki-timeout: "1s"
        labels: "job=krakend,service=api-gateway"
    environment:
      - FC_ENABLE=1
      - FC_SETTINGS=config/settings
      - FC_PARTIALS=config/partials
      - FC_TEMPLATES=config/templates
      - FC_OUT=out.json
      - SERVICE_NAME=KrakenD API Gateway
    command: [ "run", "-dc", "krakend.tmpl", "" ]
